"""add profiles

Revision ID: 763a6f4f621e
Revises: 65eabb564480
Create Date: 2025-09-10 11:40:21.982773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763a6f4f621e'
down_revision: Union[str, Sequence[str], None] = '65eabb564480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('adspower_profile_id', sa.String(), nullable=False),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('last_opened_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_account_id'), 'profiles', ['account_id'], unique=False)
    op.create_index(op.f('ix_profiles_adspower_profile_id'), 'profiles', ['adspower_profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_adspower_profile_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_account_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
