"""merge_profile_fields_into_accounts

Revision ID: 08bd8b6e5d3e
Revises: 73d0ba782e38
Create Date: 2025-09-27 12:00:05.209249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bd8b6e5d3e'
down_revision: Union[str, Sequence[str], None] = '73d0ba782e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('bulk_profile_name', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('adspower_profile_id', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('health', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_opened_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('last_ws_puppeteer', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('last_ws_selenium', sa.String(), nullable=True))
    op.create_index(op.f('ix_accounts_adspower_profile_id'), 'accounts', ['adspower_profile_id'], unique=True)
    op.create_index(op.f('ix_accounts_bulk_profile_name'), 'accounts', ['bulk_profile_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_bulk_profile_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_adspower_profile_id'), table_name='accounts')
    op.drop_column('accounts', 'last_ws_selenium')
    op.drop_column('accounts', 'last_ws_puppeteer')
    op.drop_column('accounts', 'last_opened_at')
    op.drop_column('accounts', 'health')
    op.drop_column('accounts', 'adspower_profile_id')
    op.drop_column('accounts', 'bulk_profile_name')
    # ### end Alembic commands ###
