"""profiles: add ws fields

Revision ID: 18e8854992e4
Revises: 5aa3e194ff24
Create Date: 2025-09-10 15:50:28.691222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e8854992e4'
down_revision: Union[str, Sequence[str], None] = '5aa3e194ff24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('last_ws_puppeteer', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('last_ws_selenium', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'last_ws_selenium')
    op.drop_column('profiles', 'last_ws_puppeteer')
    # ### end Alembic commands ###
