"""fix_action_logs_profile_foreign_key

Revision ID: 42720227c8a2
Revises: 08bd8b6e5d3e
Create Date: 2025-09-27 16:15:04.811626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42720227c8a2'
down_revision: Union[str, Sequence[str], None] = '08bd8b6e5d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('action_logs_profile_id_fkey', 'action_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('action_logs_profile_id_fkey', 'action_logs', 'profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
