"""add_instagram_username_column

Revision ID: 6a35ce6471c7
Revises: 921fc21d0e41
Create Date: 2025-10-01 00:15:42.587266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a35ce6471c7'
down_revision: Union[str, Sequence[str], None] = '921fc21d0e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('instagram_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'instagram_username')
    # ### end Alembic commands ###
