"""fix_profile_account_foreign_key_cascade

Revision ID: 73d0ba782e38
Revises: cc064f5b5d32
Create Date: 2025-09-26 19:56:02.434363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d0ba782e38'
down_revision: Union[str, Sequence[str], None] = 'cc064f5b5d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_profiles_adspower_profile_id', 'profiles', type_='unique')
    op.drop_index('ux_profiles_one_per_account', table_name='profiles', postgresql_where='(account_id IS NOT NULL)')
    op.drop_constraint('profiles_account_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_account_id_fkey', 'profiles', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.create_index('ux_profiles_one_per_account', 'profiles', ['account_id'], unique=True, postgresql_where='(account_id IS NOT NULL)')
    op.create_unique_constraint('uq_profiles_adspower_profile_id', 'profiles', ['adspower_profile_id'])
    # ### end Alembic commands ###
