"""remove_adspower_profile_id_column

Revision ID: 921fc21d0e41
Revises: 42720227c8a2
Create Date: 2025-09-30 23:47:13.722944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921fc21d0e41'
down_revision: Union[str, Sequence[str], None] = '42720227c8a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_adspower_profile_id', table_name='accounts')
    op.drop_column('accounts', 'adspower_profile_id')
    op.alter_column('profiles', 'adspower_profile_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_profiles_bulk_profile_name', table_name='profiles')
    op.drop_constraint('profiles_account_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'accounts', ['account_id'], ['id'])
    op.drop_column('profiles', 'bulk_profile_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bulk_profile_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_account_id_fkey', 'profiles', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_profiles_bulk_profile_name', 'profiles', ['bulk_profile_name'], unique=True)
    op.alter_column('profiles', 'adspower_profile_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('accounts', sa.Column('adspower_profile_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_accounts_adspower_profile_id', 'accounts', ['adspower_profile_id'], unique=True)
    # ### end Alembic commands ###
